import type { FieldDef } from "@minions/core";
import {
  AtSign,
  BadgeCheck,
  Building2,
  Calendar,
  CircleUser,
  Cloud,
  Code2,
  CreditCard,
  Database,
  FileText,
  Fingerprint,
  Globe,
  Hash,
  KeyRound,
  Landmark,
  Layers,
  LifeBuoy,
  Link2,
  type LucideIcon,
  Mail,
  MapPin,
  Phone,
  Plug,
  ScrollText,
  Server,
  ShieldCheck,
  SlidersHorizontal,
  Terminal,
  Timer,
  ToggleRight,
  User,
  Webhook,
} from "lucide-react";

// Specific keys first, then the field's kind.
const BY_KEY: Record<string, LucideIcon> = {
  provider: Building2,
  registrar: Building2,
  issuer: Building2,
  service: Building2,
  software: BadgeCheck,
  bank: Landmark,
  domain: AtSign,
  host: Server,
  port: Hash,
  database: Database,
  engine: Database,
  connection_string: Plug,
  private_key: Terminal,
  public_key: Terminal,
  passphrase: KeyRound,
  fingerprint: Fingerprint,
  environment: Layers,
  status: SlidersHorizontal,
  region: MapPin,
  account_id: Hash,
  account: CircleUser,
  licensed_to: CircleUser,
  cardholder: CircleUser,
  account_name: CircleUser,
  recovery_phone: Phone,
  backup_codes: LifeBuoy,
  codes: LifeBuoy,
  permissions: ShieldCheck,
  endpoint: Webhook,
  events: Webhook,
  nameservers: Server,
  billing_address: MapPin,
  notes: ScrollText,
  content: FileText,
  ssl: ShieldCheck,
  console_url: Cloud,
};

const BY_KIND: Record<FieldDef["kind"], LucideIcon> = {
  text: FileText,
  url: Globe,
  email: Mail,
  username: User,
  password: KeyRound,
  secret: KeyRound,
  totp: Timer,
  multiline: ScrollText,
  number: Hash,
  date: Calendar,
  select: SlidersHorizontal,
  boolean: ToggleRight,
  "card-number": CreditCard,
  cvv: ShieldCheck,
  month: Calendar,
  year: Calendar,
  code: Code2,
};

export function fieldIcon(def: Pick<FieldDef, "key" | "kind">): LucideIcon {
  if (def.key.startsWith("var.")) return Code2;
  if (def.key.startsWith("custom.")) return Link2;
  return BY_KEY[def.key] ?? BY_KIND[def.kind] ?? FileText;
}
